### ISSUE TITLE
cummulative gpa needs research

### ISSUE THREAD

**Issue by HemanginiShah** [tl-its-umich-edu/canvas_queries#12]
Cumulative gpa from the SQLViews when pulled into Tableau, it displays different values and also pulls in for each course.  It should be at the student academic level, not course level.
https://docs.google.com/document/d/18ydhRu0ulpUiLhvXUjzJbbXYTj_8VKvR3VwZEdphTG4/edit

**Comment by pushyamig** [comment]
The changes are merged to Main branch and things are verified as well
